name: riverpod2_persist_storage
description: riverpod2_persist storage package
version: 1.0.0
repository: https://github.com/PetverseAI/orca_app/riverpod2_persist

environment:
  sdk: ^3.5.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^5.0.0

