name: riverpod2_persist_generator
description: riverpod2_persist generator package
version: 1.0.1
repository: https://github.com/PetverseAI/riverpod2_persist

environment:
  sdk: ^3.5.0

resolution: workspace

# Add regular dependencies here.
dependencies:
  analyzer: ^6.7.0
  build: ^2.4.1
  collection: ^1.18.0
  meta: ^1.15.0
  path: ^1.9.0
  riverpod: ^2.6.1
  riverpod_analyzer_utils: ^0.5.6
  riverpod_generator: ^2.6.1
  source_gen: ^1.5.0
  riverpod2_persist_annotation: 1.0.1

dev_dependencies:
  lints: ^5.0.0
